micronaut:
  application:
    name: appSerwer
    instance:
      zone: "Europe/Warsaw"
  router:
    static-resources:
      default:
        enabled: false #true
        paths: classpath:public
        mapping: "/**"
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:VVUd6u/FWiFV3X6VaFl9U+xdSBBeSQQFwwH+qdIg3xM=}
              base64: true
              jws-algorithm: HS256
    reject-not-found: false
    redirect:
      login-success: /
      login-failure: /login/authFailed
      logout: /
      prior-to-login: false
      forbidden:
        enabled: false
      unauthorized:
        enabled: false
    endpoints:
      logout:
        enabled: true # def value true
        get-allowed: true
      login:
        enabled: true # def value true
  #        path: "/api/v1/device/login" # def value "/login"
  #microstream:
  #  storage:
  #    main:
  #      root-class: 'example.micronaut.FruitContainer'
  #      storage-directory: 'build/fruit-storage'
  server:
    host: "localhost"
    port: 8080
    max-request-size: 65536
    multipart:
      enabled: true
      max-file-size: 65536
      mixed: true
      disk: true
      threshold: 256
netty:
  default:
    allocator:
      max-order: 3
mongodb:
  uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"
# Custom properties
db:
  name: 'app'
  user-collection: 'user'
  group-collection: 'group'
  page-collection: 'page'
  post-collection: 'post'
  watch-collection: 'watch'
  reel-collection: 'reel'
  snap-collection: 'snap'
  story-collection: 'story'
  album-collection: 'album'
  song-collection: 'song'
  video-collection: 'video'
  image-collection: 'image'
  audio-collection: 'audio'
  communicator-collection: 'communicator'
  reset-password-collection: 'reset-password'
  user-history-collection: 'user-history-collection'
  group-history-collection: 'group-history-collection'
user-defaults:
  role: "def"