micronaut:
  application:
    name: appServer
    instance:
      zone: "Europe/Warsaw"
  router:
    static-resources:
      default:
        enabled: false #true
        paths: classpath:public
        mapping: "/**"
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:VVUd6u/FWiFV3X6VaFl9U+xdSBBeSQQFwwH+qdIg3xM=}
              base64: true
              jws-algorithm: HS256
    reject-not-found: false
    redirect:
      login-success: /
      login-failure: /login/authFailed
      logout: /
      prior-to-login: false
      forbidden:
        enabled: false
      unauthorized:
        enabled: false
    endpoints:
      logout:
        enabled: true # def value true
        get-allowed: true
      login:
        enabled: true # def value true
  #        path: "/api/v1/device/login" # def value "/login"
  #microstream:
  #  storage:
  #    main:
  #      root-class: 'example.micronaut.FruitContainer'
  #      storage-directory: 'build/fruit-storage'
  server:
    host: "localhost"
    port: 8080
    max-request-size: 65536
    multipart:
      enabled: true
      max-file-size: 65536
      mixed: true
      disk: true
      threshold: 256
  email:
    from:
      email: ""
      name: ""
netty:
  default:
    allocator:
      max-order: 3
javamail:
  authentication:
    username: 'my.username'
    password: 'my.password'
email:
  forgot-password:
    template: "forgot-password"
    subject: "Reset your App Account password"
service:
  default-feed-limit: 12
mongodb:
  uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"
db:
  name: 'app'
  user-collection: 'user'
  user-profile-collection: 'user-profile'
  user-friends-collection: 'user-friends'
  group-collection: 'group'
  page-collection: 'page'
  post-collection: 'post'
  watch-collection: 'watch'
  reel-collection: 'reel'
  snap-collection: 'snap'
  story-collection: 'story'
  song-collection: 'song'
  video-collection: 'video'
  image-collection: 'image'
  audio-collection: 'audio'
  communicator-collection: 'communicator'
  comments-collection: "comments"
  reset-password-collection: 'reset-password'
  upload-transaction-collection: 'upload-transaction'
  user-history-collection: 'user-history'
  group-history-collection: 'group-history'
  page-history-collection: 'page-history'
  post-history-collection: 'post-history'
  reel-history-collection: 'reel-history'
  snap-history-collection: 'snap-history'
  song-history-collection: 'song-history'
  story-history-collection: 'story-history'
  watch-history-collection: 'watch-history'
  group-rules-collection: 'group-rules'
  comment-history-collection: 'comment-history'
  notification-collection: 'notification'
  report-user-collection: 'report-user'
  report-group-collection: 'report-group'
  report-page-collection: 'report-page'
  report-post-collection: 'report-post'
  report-watch-collection: 'report-watch'
  report-reel-collection: 'report-reel'
  report-snap-collection: 'report-snap'
  report-story-collection: 'report-story'
  report-song-collection: 'report-song'
  report-video-collection: 'report-video'
  report-image-collection: 'report-image'
  report-audio-collection: 'report-audio'
user-defaults:
  role: "def"